In [1]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

ds= pd.read_csv("Pedestrian_Counting_System___2009_to_Present__counts_per_hour_.csv")
ds.head()

ID               Date_Time  Year Month  Mdate     Day  Time  Sensor_ID  \
0   1  05/01/2009 12:00:00 AM  2009   May      1  Friday     0          1   
1   2  05/01/2009 12:00:00 AM  2009   May      1  Friday     0          2   
2   3  05/01/2009 12:00:00 AM  2009   May      1  Friday     0          4   
3   4  05/01/2009 12:00:00 AM  2009   May      1  Friday     0          5   
4   5  05/01/2009 12:00:00 AM  2009   May      1  Friday     0          6   

                         Sensor_Name  Hourly_Counts  
0         Bourke Street Mall (North)           53.0  
1         Bourke Street Mall (South)           52.0  
2                   Town Hall (West)          209.0  
3                     Princes Bridge          157.0  
4  Flinders Street Station Underpass          139.0

In [2]:
ds=ds[ds.Sensor_ID==3]
ds.head()

ID               Date_Time  Year Month  Mdate      Day  Time  \
6482  6483  05/19/2009 12:00:00 AM  2009   May     19  Tuesday     0   
6498  6499  05/19/2009 01:00:00 AM  2009   May     19  Tuesday     1   
6514  6515  05/19/2009 02:00:00 AM  2009   May     19  Tuesday     2   
6530  6531  05/19/2009 03:00:00 AM  2009   May     19  Tuesday     3   
6546  6547  05/19/2009 04:00:00 AM  2009   May     19  Tuesday     4   

      Sensor_ID        Sensor_Name  Hourly_Counts  
6482          3  Melbourne Central           90.0  
6498          3  Melbourne Central           56.0  
6514          3  Melbourne Central           31.0  
6530          3  Melbourne Central            8.0  
6546          3  Melbourne Central           31.0

In [3]:
ds = ds[ds.Time != 0]
ds = ds[ds.Time != 1]
ds = ds[ds.Time != 2]
ds = ds[ds.Time != 3]
ds = ds[ds.Time != 4]
ds = ds[ds.Time != 5]
ds = ds[ds.Time != 6]
ds.head()

ID               Date_Time  Year Month  Mdate      Day  Time  \
6594  6595  05/19/2009 07:00:00 AM  2009   May     19  Tuesday     7   
6610  6611  05/19/2009 08:00:00 AM  2009   May     19  Tuesday     8   
6626  6627  05/19/2009 09:00:00 AM  2009   May     19  Tuesday     9   
6642  6643  05/19/2009 10:00:00 AM  2009   May     19  Tuesday    10   
6658  6659  05/19/2009 11:00:00 AM  2009   May     19  Tuesday    11   

      Sensor_ID        Sensor_Name  Hourly_Counts  
6594          3  Melbourne Central          323.0  
6610          3  Melbourne Central          764.0  
6626          3  Melbourne Central          779.0  
6642          3  Melbourne Central         1068.0  
6658          3  Melbourne Central         1572.0

In [4]:
X=ds.iloc[:,[3,5,6]]
Y=ds.iloc[:,[9]]
print(X)

           Month        Day  Time
6594         May    Tuesday     7
6610         May    Tuesday     8
6626         May    Tuesday     9
6642         May    Tuesday    10
6658         May    Tuesday    11
6674         May    Tuesday    12
6690         May    Tuesday    13
6706         May    Tuesday    14
6722         May    Tuesday    15
6738         May    Tuesday    16
6754         May    Tuesday    17
6770         May    Tuesday    18
6786         May    Tuesday    19
6802         May    Tuesday    20
6818         May    Tuesday    21
6834         May    Tuesday    22
6850         May    Tuesday    23
6978         May  Wednesday     7
6994         May  Wednesday     8
7010         May  Wednesday     9
7026         May  Wednesday    10
7042         May  Wednesday    11
7058         May  Wednesday    12
7074         May  Wednesday    13
7090         May  Wednesday    14
7106         May  Wednesday    15
7122         May  Wednesday    16
7138         May  Wednesday    17
7154         M

In [5]:
from sklearn import preprocessing
le_X=preprocessing.LabelEncoder()
z=le_X.fit_transform(X.values[:,0])
X.iloc[:,0]=z

a=le_X.fit_transform(X.values[:,1])
X.iloc[:,1]=a

b=le_X.fit_transform(X.values[:,2])
X.iloc[:,2]=b

print(X)

         Month  Day  Time
6594         8    5     0
6610         8    5     1
6626         8    5     2
6642         8    5     3
6658         8    5     4
6674         8    5     5
6690         8    5     6
6706         8    5     7
6722         8    5     8
6738         8    5     9
6754         8    5    10
6770         8    5    11
6786         8    5    12
6802         8    5    13
6818         8    5    14
6834         8    5    15
6850         8    5    16
6978         8    6     0
6994         8    6     1
7010         8    6     2
7026         8    6     3
7042         8    6     4
7058         8    6     5
7074         8    6     6
7090         8    6     7
7106         8    6     8
7122         8    6     9
7138         8    6    10
7154         8    6    11
7170         8    6    12
...        ...  ...   ...
2544344      4    6     4
2544393      4    6     5
2544442      4    6     6
2544491      4    6     7
2544540      4    6     8
2544589      4    6     9
2544638     

C:\Users\Sahil\Anaconda3\lib\site-packages\pandas\core\indexing.py:543: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item] = s
C:\Users\Sahil\Anaconda3\lib\site-packages\pandas\core\indexing.py:630: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self.obj[item_labels[indexer[info_axis]]] = value


In [6]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder(categorical_features = [0,1,2])
X=ohe.fit_transform(X).toarray()
print(X)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]


In [7]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(X,Y,test_size=0.2,random_state=20)
X_train=np.array(X_train)
Y_train=np.array(Y_train)

In [8]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
#y_pred1 = LinReg.fit(X_train1.reshape(-1,1), y_train1)
#X_train=X_train.reshape(-1,1)
X_train=np.array(X_train)
Y_train=np.array(Y_train)
X_test=np.array(X_test)
Y_test=np.array(Y_test)
reg.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [9]:
y_pred= reg.predict(X_test)

In [10]:
print(y_pred)

[[2203.]
 [1852.]
 [1608.]
 ...
 [2051.]
 [1354.]
 [2437.]]


In [11]:
accuracy = reg.score(X_test,Y_test)
print(accuracy*100,'%')

82.31186166827892 %


In [12]:
inpmnth=input()
inpmnth=int(inpmnth)
pr1=np.arange(204)
pr1=np.arange(204).reshape(17,12)

for j in range(0,17):
    for z in range(0,12):
        if(z==inpmnth):
            pr1[j][z]=1
        else:
            pr1[j][z]=0
print(pr1)

2
[[0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0]]


In [13]:
inpday=input()
inpday=int(inpday)
pr2=np.arange(119)
pr2=np.arange(119).reshape(17,7)

for j in range(0,17):
    for z in range(0,7):
        if(z==inpday):
            pr2[j][z]=1
        else:
            pr2[j][z]=0
print(pr2)

2
[[0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0]]


In [14]:
pr3=np.arange(289)
pr3=np.arange(289).reshape(17,17)

for j in range(0,17):
    for z in range(0,17):
        if(z==j):
            pr3[j][z]=1
        else:
            pr3[j][z]=0
print(pr3)

[[1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1]]


In [15]:
pr4=np.concatenate((pr1, pr2), axis=1)
pr=np.concatenate((pr4,pr3),axis=1)
print(pr)

[[0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0 0 0

In [16]:
y_pred1= reg.predict(pr)
print(y_pred1)

[[ 371.]
 [ 703.]
 [ 809.]
 [1073.]
 [1466.]
 [2313.]
 [2540.]
 [2379.]
 [2369.]
 [2377.]
 [2550.]
 [2437.]
 [2142.]
 [1917.]
 [1608.]
 [1222.]
 [ 867.]]


In [17]:
from sklearn.ensemble import RandomForestRegressor
reg2=RandomForestRegressor(n_estimators=100,random_state=0)
reg2.fit(X_test,Y_test)

C:\Users\Sahil\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  This is separate from the ipykernel package so we can avoid doing imports until


RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=1,
           oob_score=False, random_state=0, verbose=0, warm_start=False)

In [18]:
accuracy = reg2.score(X_test,Y_test)
print(accuracy*100,'%')

89.63185978536046 %


In [19]:
y_pred2= reg2.predict(pr)
print(y_pred2)

[ 265.11389286  311.44185534  547.29402303  817.47235442 1161.49849075
 1968.65341667 2516.9680184  2246.94945635 2461.68295151 2157.70884127
 2109.39830256 2048.24006304 2192.06976506 1903.07663095 2116.67762291
 1490.24009019 1501.72693494]
